// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisaEleitoral_v2.Data;

#nullable disable

namespace PesquisaEleitoral_v2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516140023_CriandoBanco")]
    partial class CriandoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CandidatoPesquisa", b =>
                {
                    b.Property<int>("CandidatosCandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("PesquisaCandidatosPesquisaId")
                        .HasColumnType("int");

                    b.HasKey("CandidatosCandidatoId", "PesquisaCandidatosPesquisaId");

                    b.HasIndex("PesquisaCandidatosPesquisaId");

                    b.ToTable("CandidatoPesquisa");
                });

            modelBuilder.Entity("PesquisaEleitoral_v2.Models.Candidato", b =>
                {
                    b.Property<int>("CandidatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidatoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("CandidatoId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("PesquisaEleitoral_v2.Models.Eleitor", b =>
                {
                    b.Property<int>("EleitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EleitorId"));

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Regiao")
                        .HasColumnType("int");

                    b.Property<decimal>("Renda")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("EleitorId");

                    b.ToTable("Eleitores");
                });

            modelBuilder.Entity("PesquisaEleitoral_v2.Models.IntencaoDeVoto", b =>
                {
                    b.Property<int>("IntencaoDeVotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IntencaoDeVotoId"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EleitorId")
                        .HasColumnType("int");

                    b.Property<int>("PesquisaId")
                        .HasColumnType("int");

                    b.HasKey("IntencaoDeVotoId");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleitorId");

                    b.HasIndex("PesquisaId");

                    b.ToTable("IntencoesDeVoto");
                });

            modelBuilder.Entity("PesquisaEleitoral_v2.Models.Pesquisa", b =>
                {
                    b.Property<int>("PesquisaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PesquisaId"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PesquisaId");

                    b.ToTable("Pesquisas");
                });

            modelBuilder.Entity("CandidatoPesquisa", b =>
                {
                    b.HasOne("PesquisaEleitoral_v2.Models.Candidato", null)
                        .WithMany()
                        .HasForeignKey("CandidatosCandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaEleitoral_v2.Models.Pesquisa", null)
                        .WithMany()
                        .HasForeignKey("PesquisaCandidatosPesquisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PesquisaEleitoral_v2.Models.IntencaoDeVoto", b =>
                {
                    b.HasOne("PesquisaEleitoral_v2.Models.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaEleitoral_v2.Models.Eleitor", "Eleitor")
                        .WithMany("IntencoesDeVoto")
                        .HasForeignKey("EleitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaEleitoral_v2.Models.Pesquisa", "Pesquisa")
                        .WithMany()
                        .HasForeignKey("PesquisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleitor");

                    b.Navigation("Pesquisa");
                });

            modelBuilder.Entity("PesquisaEleitoral_v2.Models.Eleitor", b =>
                {
                    b.Navigation("IntencoesDeVoto");
                });
#pragma warning restore 612, 618
        }
    }
}
